[package]
name = "julia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gif = "0.12.0"
image = "0.24.6"
num = "0.4.0"
substring = "1.4.5"
threadpool = "1.8.1"
